### PR TITLE
Extend FpML root element logic

### LINKED ISSUE #1351: Support FPML documents having clearingStatus as root node
Currently, the Strata FpmlDocumentParser expects the root node to include both `trade` and `party` elements.

I'm working with an FPML document having a structure similar to the one below, and Strata fails when trying to parse it:
```
<clearingStatus ...>
  <clearingStatusItem>
    <trade>
      ...
    </trade>
  </clearingStatusItem>
  <party>
    ...
  </party>
</clearingStatus>
```

### PR DESCRIPTION
**Pull request by jodastephen**
Allow party and trade elements to be separated
Fixes #1351

### CODE REVIEW

File: modules/loader/src/main/java/com/opengamma/strata/loader/fpml/FpmlDocumentParser.java [hunk 1]
```diff
@@ -195,29 +196,60 @@ private FpmlDocumentParser(
 
   // intelligently finds the FpML root element
   private static XmlElement findFpmlRoot(XmlElement root) {
-    if (isFpmlRoot(root)) {
-      return root;
+    XmlElement fpmlRoot = isFpmlRoot(root);
```
Comment (andreiruse) [inline modules/loader/src/main/java/com/opengamma/strata/loader/fpml/FpmlDocumentParser.java]: Since `isFpmlRoot()` doesn't return a boolean anymore, is it worth renaming it to something more appropriate, such as `getFpmlRoot()`?
