### PR TITLE
Fix MultiCurrencyAmountArray.size() when built from empty amounts

### LINKED ISSUE #1312: MultiCurrencyAmountArray.of(size, fn) doesn't work with empty MultiCurrencyAmounts
The following code produces a `MultiCurrencyAmountArray` of size zero even though it is created from two `MultiCurrencyAmounts`

    MultiCurrencyAmountArray array = MultiCurrencyAmountArray.of(
        MultiCurrencyAmount.empty(),
        MultiCurrencyAmount.empty());

The following code always produces a `MultiCurrencyAmountArray` with a size of zero regardless of the requested size:

    MultiCurrencyAmountArray.of(size, () -> MultiCurrencyAmount.empty());

The size of the array is derived from the size of the internal arrays holding the currency values. If there are no values a size of zero is incorrectly returned.

### PR DESCRIPTION
**Pull request by cjkent**
`MultiCurrencyAmountArray.size()` uses the size of the amounts for one of its currencies. This means it incorrectly reports a size of zero if it is built from multiple empty `MultiCurrencyAmount` instances or if the function passed to the factory method returns empty amounts.

This PR fixes the logic to retain the size even if the amounts are all empty.

Fixes #1312

### CODE REVIEW

File: modules/basics/src/main/java/com/opengamma/strata/basics/currency/MultiCurrencyAmountArray.java [hunk 1]
```diff
@@ -56,14 +56,16 @@
     implements FxConvertible<CurrencyAmountArray>, ImmutableBean, Serializable {
 
   /**
+   * This size of the array.
```
Comment (jonathansenior) [inline modules/basics/src/main/java/com/opengamma/strata/basics/currency/MultiCurrencyAmountArray.java]: "This" and "the" seem to be transposed.

File: modules/basics/src/main/java/com/opengamma/strata/basics/currency/MultiCurrencyAmountArray.java [hunk 2]
```diff
@@ -56,14 +56,16 @@
     implements FxConvertible<CurrencyAmountArray>, ImmutableBean, Serializable {
 
   /**
+   * The size of this array.
```
Comment (jonathansenior) [inline modules/basics/src/main/java/com/opengamma/strata/basics/currency/MultiCurrencyAmountArray.java]: What are the semantics of `size` supposed to be in this class? It looks like the previous semantics were that `size` was the number of currencies, i.e. consistent with `size` on `MultiCurrencyAmount`. Now it seems to be either this, or the number of `MultiCurrencyAmount` items (i.e. scenarios) that it was constructed from, depending on how it is constructed.

File: modules/basics/src/main/java/com/opengamma/strata/basics/currency/MultiCurrencyAmountArray.java [hunk 3]
```diff
@@ -129,7 +131,7 @@ public static MultiCurrencyAmountArray of(int size, IntFunction<MultiCurrencyAmo
    */
   public static MultiCurrencyAmountArray of(Map<Currency, DoubleArray> values) {
     values.values().stream().reduce((a1, a2) -> checkSize(a1, a2));
-    return new MultiCurrencyAmountArray(values);
+    return new MultiCurrencyAmountArray(values.size(), values);
```
Comment (jonathansenior) [inline modules/basics/src/main/java/com/opengamma/strata/basics/currency/MultiCurrencyAmountArray.java]: Here, `size` is the number of currencies.

File: modules/basics/src/main/java/com/opengamma/strata/basics/currency/MultiCurrencyAmountArray.java [hunk 4]
```diff
@@ -93,7 +95,7 @@ public static MultiCurrencyAmountArray of(List<MultiCurrencyAmount> amounts) {
       }
     }
     Map<Currency, DoubleArray> doubleArrayMap = MapStream.of(valueMap).mapValues(v -> DoubleArray.ofUnsafe(v)).toMap();
-    return new MultiCurrencyAmountArray(doubleArrayMap);
+    return new MultiCurrencyAmountArray(size, doubleArrayMap);
```
Comment (jonathansenior) [inline modules/basics/src/main/java/com/opengamma/strata/basics/currency/MultiCurrencyAmountArray.java]: Here, `size` is the number of `MultiCurrencyAmount` items in the input list.

File: modules/basics/src/main/java/com/opengamma/strata/basics/currency/MultiCurrencyAmountArray.java (hunk 3 above)
Comment (cjkent) [inline modules/basics/src/main/java/com/opengamma/strata/basics/currency/MultiCurrencyAmountArray.java]: This is wrong, it's supposed to be the number of currency amounts. This should be the size of one of the values in `values`.

File: modules/basics/src/main/java/com/opengamma/strata/basics/currency/MultiCurrencyAmountArray.java (hunk 2 above)
Comment (jonathansenior) [inline modules/basics/src/main/java/com/opengamma/strata/basics/currency/MultiCurrencyAmountArray.java]: Actually I'm wrong here about the semantics - it used to be the size of the array which is in practice the number of scenarios. After your updates this is now the case everywhere, so I will merge.
