### PR TITLE
Fixed coupon bond: provider and pricer

### LINKED ISSUE #186: Bonds - trade and product model

### LINKED ISSUE #187: Bond - support for PV and risk measures

### PR DESCRIPTION
**Pull request by yukiiwashita**
* Added bond-specific rate provider, **LegalEntityDiscountingProvider**, which produces two types of discount factors **repoCurveDiscountFactors** and **IssuerCurveDiscountFactors**. 
* Added bond pricer, **DiscountingFixedCouponBondTradePricer**, where each coupon payment is computed by **DiscountingFixedCouponBondPaymentPeriodPricer**. 
* Dirty price and its derivative computation from yield is tested against 2.x
* This work closes #421 
* This work closes #186 
* This work closes #187

### CODE REVIEW

File: modules/finance/src/main/java/com/opengamma/strata/finance/rate/bond/FixedCouponBondTrade.java [hunk 1]
```diff
@@ -456,14 +513,31 @@ public Builder quantity(long quantity) {
       return this;
     }
 
+    /**
+     * Sets the upfront fee payment of the bond trade.
+     * <p>
+     * The payment sign should be compatible with the product buy/sell flag, i.e. payment is negative for buy and
+     * positive for sell bond.
```
Comment (marc-opengamma) [inline modules/finance/src/main/java/com/opengamma/strata/finance/rate/bond/FixedCouponBondTrade.java]: Replace with: "The payment sign should be compatible with the product quantity, i.e. payment is negative for positive quantity and positive for negative quantity."

File: modules/finance/src/test/java/com/opengamma/strata/finance/rate/bond/FixedCouponBondTradeTest.java [hunk 2]
```diff
@@ -74,6 +77,7 @@
       .build();
   private static final Security<FixedCouponBond> BOND_SECURITY =
       UnitSecurity.builder(PRODUCT).standardId(SECURITY_ID).build();
+  private static final Payment UPFRONT_PAYMENT = Payment.of(CurrencyAmount.of(EUR, -NOTIONAL * 0.065), SETTLEMENT_DATE);
```
Comment (marc-opengamma) [inline modules/finance/src/test/java/com/opengamma/strata/finance/rate/bond/FixedCouponBondTradeTest.java]: Tests should have realistic values: payment amount = -NOTIONAL * QUANTITY * 0.99 or something similar.

File: modules/finance/src/test/java/com/opengamma/strata/finance/rate/bond/FixedCouponBondTradeTest.java [hunk 3]
```diff
@@ -152,6 +163,7 @@ public void coverage() {
             .standardId(StandardId.of("Ticker", "GOV1-BND1"))
             .build()))
         .quantity(100L)
+        .payment(Payment.of(CurrencyAmount.of(EUR, NOTIONAL * 0.05), SETTLEMENT_DATE))
```
Comment (marc-opengamma) [inline modules/finance/src/test/java/com/opengamma/strata/finance/rate/bond/FixedCouponBondTradeTest.java]: Tests should have realistic values: payment amount = -NOTIONAL * QUANTITY * 0.99 or something similar.

File: modules/pricer/src/main/java/com/opengamma/strata/pricer/rate/LegalEntityDiscountingProvider.java [hunk 4]
```diff
@@ -0,0 +1,735 @@
...
+        throw new IllegalArgumentException("No map to the legal entity group from ID: " + entry.getKey().getFirst());
+      }
+    }
+  }
+
+  //-------------------------------------------------------------------------
+  /**
+   * Gets the discount factors of a repo curve for standard IDs and a currency.
+   * <p>
+   * If the valuation date is on or after the specified date, the discount factor is 1.
```
Comment (marc-opengamma) [inline modules/pricer/src/main/java/com/opengamma/strata/pricer/rate/LegalEntityDiscountingProvider.java]: Change doc: If the bond standard ID is matched in a BondGroup, the relevant DiscountFactors is returned, if not the issuer standard ID is checked and the relevant DiscountFactors is returned; if both the bond and the issuer ID are not in any BondGroup, an error is thrown.

File: modules/pricer/src/main/java/com/opengamma/strata/pricer/rate/bond/DiscountingFixedCouponBondTradePricer.java [hunk 5]
```diff
@@ -0,0 +1,1076 @@
...
+    return CurrencyAmount.of(product.getCurrency(), total);
+  }
+
+  private CurrencyAmount presentValueNominal(
+      ExpandedFixedCouponBond product,
+      IssuerCurveDiscountFactors discountFactors,
+      LocalDate settlementDate) {
+
+    Payment nominal = product.getNominalPayment();
+    if (!settlementDate.isAfter(nominal.getDate())) {
```
Comment (marc-opengamma) [inline modules/pricer/src/main/java/com/opengamma/strata/pricer/rate/bond/DiscountingFixedCouponBondTradePricer.java]: We may want to add that check in the trade builder, but I don't think this check is required at the pricing level.

File: modules/pricer/src/main/java/com/opengamma/strata/pricer/rate/bond/DiscountingFixedCouponBondTradePricer.java [hunk 6]
```diff
@@ -0,0 +1,1076 @@
...
+    for (FixedCouponBondPaymentPeriod period : product.getPeriodicPayments()) {
+      if ((exCoupon && !settlementDate.isAfter(period.getDetachmentDate())) ||
+          (!exCoupon && period.getPaymentDate().isAfter(settlementDate))) {
+        total += periodPricer.presentValueWithSpread(period, discountFactors, zSpread, periodic, periodsPerYear);
+      }
+    }
+    return CurrencyAmount.of(product.getCurrency(), total);
+  }
+
+  private CurrencyAmount presentValueNominal(
```
Comment (marc-opengamma) [inline modules/pricer/src/main/java/com/opengamma/strata/pricer/rate/bond/DiscountingFixedCouponBondTradePricer.java]: Do we need a private method for a 1 line formula?

File: modules/pricer/src/main/java/com/opengamma/strata/pricer/rate/bond/DiscountingFixedCouponBondTradePricer.java [hunk 7]
```diff
@@ -0,0 +1,1076 @@
...
+   * The present value of the trade is the value on the valuation date.
+   * The result is expressed using the payment currency of the bond.
+   * <p>
+   * The computation uses {@code settlementDate}. Thus {@code tradeInfo} in the trade must not be empty.
+   * 
+   * @param trade  the trade to price
+   * @param provider  the rates provider
+   * @return the present value of the fixed coupon bond trade
+   */
+  public CurrencyAmount presentValueProduct(FixedCouponBondTrade trade, LegalEntityDiscountingProvider provider) {
```
Comment (marc-opengamma) [inline modules/pricer/src/main/java/com/opengamma/strata/pricer/rate/bond/DiscountingFixedCouponBondTradePricer.java]: For "presentValueProduct", only the Product should be passed.

File: modules/pricer/src/main/java/com/opengamma/strata/pricer/rate/bond/DiscountingFixedCouponBondTradePricer.java [hunk 8]
```diff
@@ -0,0 +1,1076 @@
...
+   * The computation uses {@code settlementDate}. Thus {@code tradeInfo} in the trade must not be empty.
+   * 
+   * @param trade  the trade to price
+   * @param provider  the rates provider
+   * @return the present value of the fixed coupon bond trade
+   */
+  public CurrencyAmount presentValue(FixedCouponBondTrade trade, LegalEntityDiscountingProvider provider) {
+    CurrencyAmount pvProduct = presentValueProduct(trade, provider);
+    CurrencyAmount pvPayment = presentValuePayment(trade, provider);
+    return pvProduct.plus(pvPayment);
```
Comment (marc-opengamma) [inline modules/pricer/src/main/java/com/opengamma/strata/pricer/rate/bond/DiscountingFixedCouponBondTradePricer.java]: Isn't the trade "quantity" missing?

File: modules/pricer/src/main/java/com/opengamma/strata/pricer/rate/bond/DiscountingFixedCouponBondTradePricer.java [hunk 9]
```diff
@@ -0,0 +1,1076 @@
...
+   * @param provider  the rates provider
+   * @param cleanPrice  the clean price.
+   * @return the present value of the fixed coupon bond trade
+   */
+  public CurrencyAmount presentValueProductFromCleanPrice(
+      FixedCouponBondTrade trade,
+      LegalEntityDiscountingProvider provider,
+      double cleanPrice) {
+    FixedCouponBond product = trade.getProduct();
+    LocalDate settlementDate = trade.getTradeInfo().getSettlementDate().get();
```
Comment (marc-opengamma) [inline modules/pricer/src/main/java/com/opengamma/strata/pricer/rate/bond/DiscountingFixedCouponBondTradePricer.java]: The pvFromCleanPrice should apply at the standard settlement date of the bond security, not at trade settlement date.

File: modules/pricer/src/main/java/com/opengamma/strata/pricer/rate/bond/DiscountingFixedCouponBondTradePricer.java [hunk 10]
```diff
@@ -0,0 +1,1076 @@
...
+    StandardId securityId = trade.getSecurityLink().getStandardId();
+    StandardId legalEntityId = product.getLegalEntityId();
+    double df = provider.repoCurveDiscountFactors(
+        securityId, legalEntityId, product.getCurrency()).discountFactor(settlementDate);
+    double pvPrice = (cleanPrice * product.getNotional() + accruedInterest(trade)) * df;
```
Comment (marc-opengamma) [inline modules/pricer/src/main/java/com/opengamma/strata/pricer/rate/bond/DiscountingFixedCouponBondTradePricer.java]: Accrued interest should be the accrued at standard settlement date (not original settlement date).

File: modules/pricer/src/main/java/com/opengamma/strata/pricer/rate/bond/DiscountingFixedCouponBondTradePricer.java [hunk 11]
```diff
@@ -0,0 +1,1076 @@
...
+  //-------------------------------------------------------------------------
+  /**
+   * Calculates the accrued interest of the fixed coupon bond trade.
+   * <p>
+   * The computation is based on {@code settlementDate}. Thus {@code tradeInfo} in the trade must not be empty.
+   * 
+   * @param trade  the trade to price
+   * @return the accrued interest of the trade 
+   */
+  public double accruedInterest(FixedCouponBondTrade trade) {
```
Comment (marc-opengamma) [inline modules/pricer/src/main/java/com/opengamma/strata/pricer/rate/bond/DiscountingFixedCouponBondTradePricer.java]: Should have a version of "accrued interest" based on product and arbitrary date.

File: modules/pricer/src/main/java/com/opengamma/strata/pricer/rate/bond/DiscountingFixedCouponBondTradePricer.java [hunk 12]
```diff
@@ -0,0 +1,202 @@
...
+   * @param trade  the trade to price
+   * @param provider  the rates provider
+   * @param productPresentValue  the present value of the product
+   * @return  the present value of the fixed coupon bond trade
+   */
+  public CurrencyAmount presentValueFromProductPresentValue(
+      FixedCouponBondTrade trade,
+      LegalEntityDiscountingProvider provider,
+      CurrencyAmount productPresentValue) {
+    CurrencyAmount pvProduct = productPresentValue.multipliedBy(trade.getQuantity());
```
Comment (marc-opengamma) [inline modules/pricer/src/main/java/com/opengamma/strata/pricer/rate/bond/DiscountingFixedCouponBondTradePricer.java]: The product present value take into account all the coupons in the future down to today. The present value of the trade should include only the coupons that are after the settlement date/ ex-coupon date. An adjustment for those coupons is required in the present value.

File: modules/pricer/src/test/java/com/opengamma/strata/pricer/rate/bond/DiscountingFixedCouponBondTradePricerTest.java [hunk 13]
```diff
@@ -0,0 +1,323 @@
...
+
+  //-------------------------------------------------------------------------
+  public void test_presentValue() {
+    CurrencyAmount computedTrade = TRADE_PRICER.presentValue(TRADE, PROVIDER);
+    CurrencyAmount computedProduct = PRODUCT_PRICER.presentValue(PRODUCT, PROVIDER);
+    CurrencyAmount pvPayment = PRICER_NOMINAL.presentValue(UPFRONT_PAYMENT, DSC_FACTORS_REPO);
+    assertEquals(
+        computedTrade.getAmount(), computedProduct.multipliedBy(QUANTITY).plus(pvPayment).getAmount(), NOTIONAL * TOL);
+  }
+
```
Comment (marc-opengamma) [inline modules/pricer/src/test/java/com/opengamma/strata/pricer/rate/bond/DiscountingFixedCouponBondTradePricerTest.java]: The present value tests should include the case where the settlement is one day before, on and one day after the coupon payment. The same test should also be done for an ex-coupon date for a UK govt bond (with ex-coupon period).

File: modules/pricer/src/main/java/com/opengamma/strata/pricer/rate/bond/DiscountingFixedCouponBondProductPricer.java [hunk 14]
```diff
@@ -0,0 +1,894 @@
...
+   * 
+   * @param product  the product to price
+   * @param provider  the rates provider
+   * @return the present value of the fixed coupon bond product
+   */
+  public CurrencyAmount presentValue(FixedCouponBond product, LegalEntityDiscountingProvider provider) {
+    return presentValue(product, provider, provider.getValuationDate());
+  }
+
+  CurrencyAmount presentValue(
```
Comment (marc-opengamma) [inline modules/pricer/src/main/java/com/opengamma/strata/pricer/rate/bond/DiscountingFixedCouponBondProductPricer.java]: Add JavaDoc. I guess the method should be public.

File: modules/pricer/src/main/java/com/opengamma/strata/pricer/rate/bond/DiscountingFixedCouponBondProductPricer.java [hunk 15]
```diff
@@ -0,0 +1,894 @@
...
+  public CurrencyAmount presentValueWithZSpread(
+      FixedCouponBond product,
+      LegalEntityDiscountingProvider provider,
+      double zSpread,
+      boolean periodic,
+      int periodsPerYear) {
+    return presentValueWithZSpread(product, provider, zSpread, periodic, periodsPerYear, provider.getValuationDate());
+  }
+
+  CurrencyAmount presentValueWithZSpread(
```
Comment (marc-opengamma) [inline modules/pricer/src/main/java/com/opengamma/strata/pricer/rate/bond/DiscountingFixedCouponBondProductPricer.java]: Add JavaDoc. I guess the method should be public.

File: modules/pricer/src/main/java/com/opengamma/strata/pricer/rate/bond/DiscountingFixedCouponBondTradePricer.java [hunk 16]
```diff
@@ -0,0 +1,225 @@
...
+   * @param cleanPrice  the clean price.
+   * @return the present value of the fixed coupon bond trade
+   */
+  public CurrencyAmount presentValueFromCleanPrice(
+      FixedCouponBondTrade trade,
+      LegalEntityDiscountingProvider provider,
+      double cleanPrice) {
+    Security<FixedCouponBond> security = trade.getSecurity();
+    FixedCouponBond product = security.getProduct();
+    LocalDate settlementDate = trade.getTradeInfo().getSettlementDate().get();
```
Comment (marc-opengamma) [inline modules/pricer/src/main/java/com/opengamma/strata/pricer/rate/bond/DiscountingFixedCouponBondTradePricer.java]: The clean price is the price quoted at the standard settlement date.

File: modules/pricer/src/main/java/com/opengamma/strata/pricer/rate/bond/DiscountingFixedCouponBondTradePricer.java [hunk 17]
```diff
@@ -0,0 +1,225 @@
...
+    StandardId securityId = security.getStandardId();
+    StandardId legalEntityId = product.getLegalEntityId();
+    double df = provider.repoCurveDiscountFactors(
+        securityId, legalEntityId, product.getCurrency()).discountFactor(settlementDate);
+    double pvPrice = (cleanPrice * product.getNotional() + productPricer.accruedInterest(product, settlementDate)) * df;
```
Comment (marc-opengamma) [inline modules/pricer/src/main/java/com/opengamma/strata/pricer/rate/bond/DiscountingFixedCouponBondTradePricer.java]: The coupons received in the actual trade but not in the standard settlement (or the opposite) should be removed/added.
The PV of the settlement amount (pvPayment in other methods) should be added.
