### PR TITLE
Handle combined holiday calendars

### LINKED ISSUE #1295: Exception when resolving a combined holiday calendar in ImmutableReferenceData
If I create an ImmutableReferenceData instance using a pre-supplied holiday calendar, and that holiday calendar is a combined one, then a later resolve using the holiday calendar's Id (eg "Fri/Sat+Sat/Sun") will fail (because the resolver expects to just find the components and do the combining itself. There is an example unit test and stack trace below.

Now, this may be deliberate, and it is expected to create the reference data object from the basic ref data, however in this case I'm being passed a holiday calendar that was created elsewhere, and therefore don't have control over whether it is a combined one or not, and the CombinedHolidayCalendar class isn't exposed, so I can't unpack it into the constituent calendars.

    @Test
    public void testImmutableReferenceDataWithMergedHolidays() {
        HolidayCalendar hc = HolidayCalendars.FRI_SAT.combinedWith(HolidayCalendars.SAT_SUN);
        ImmutableReferenceData referenceData = ImmutableReferenceData.of(hc.getId(), hc);
        LocalDate date = BusinessDayAdjustment.of(BusinessDayConventions.PRECEDING, hc.getId()).adjust(LocalDate.of(2016, 8, 20), referenceData);
        assertEquals(LocalDate.of(2016, 8, 18), date);
    }

This exception results:

com.opengamma.strata.basics.ReferenceDataNotFoundException: Reference data not found for identifier 'Fri/Sat' of type 'HolidayCalendarId'

	at com.opengamma.strata.basics.ImmutableReferenceData.getValue(ImmutableReferenceData.java:125)
	at com.opengamma.strata.basics.date.HolidayCalendarId.lambda$null$3(HolidayCalendarId.java:96)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:474)
	at com.opengamma.strata.basics.date.HolidayCalendarId.lambda$create$4(HolidayCalendarId.java:97)
	at com.opengamma.strata.basics.date.HolidayCalendarId.resolve(HolidayCalendarId.java:166)
	at com.opengamma.strata.basics.date.BusinessDayAdjustment.adjust(BusinessDayAdjustment.java:91)

### PR DESCRIPTION
**Pull request by jodastephen**
Allow combined calendars to be looked up directly in `ReferenceData`
Allow combined identifiers to be added to `ReferenceData` and used
Optimise `ReferenceData.combinedWith` in `ImmutableReferenceData`
Fixes #1295

### CODE REVIEW

File: modules/basics/src/main/java/com/opengamma/strata/basics/date/HolidayCalendarId.java [hunk 1]
```diff
@@ -91,10 +91,21 @@ private static HolidayCalendarId create(String name) {
...
+    BiFunction<HolidayCalendarId, ReferenceData, HolidayCalendar> resolver = (id, refData) -> {
+      HolidayCalendar cal = refData.queryValueOrNull(id);
+      if (cal != null) {
+        return cal;
+      }
+      cal = HolidayCalendars.NO_HOLIDAYS;
+      for (HolidayCalendarId splitId : ids) {
+        HolidayCalendar splitCal = refData.queryValueOrNull(splitId);
+        if (splitCal == null) {
+          throw new ReferenceDataNotFoundException("");
```
Comment (cjkent) [inline modules/basics/src/main/java/com/opengamma/strata/basics/date/HolidayCalendarId.java]: Is this exception message intentionally blank?
