### PR TITLE
Fix measure name evaluation in reportin tool

### LINKED ISSUE #686: Report tool no longer suggests valid measure names
`PricingRules` has a method `configuredMeasures` which allows an application to list the available measures. This was used when parsing a trade report template to provide a helpful list of valid measure names in the failure message if the user only enters `Measures.` (almost like auto-complete) or the measure name they have chosen is invalid. This allowed report templates to be written more "interactively" through repeated running of the command-line tool. Unfortunately this behaviour has been lost in the refactoring.

### PR DESCRIPTION
**Pull request by jodastephen**
Ensure the list of available measures is returned in case of error
Fixes #686

### CODE REVIEW

File: modules/report/src/main/java/com/opengamma/strata/report/framework/expression/RootEvaluator.java [hunk 1]
```diff
@@ -56,4 +52,17 @@ public EvaluationResult evaluate(ResultsRow resultsRow, String firstToken, List<
     }
   }
 
+  // find the result starting from a measure
+  private EvaluationResult evaluateMeasures(ResultsRow resultsRow, List<String> remainingTokens) {
+    // if no measures, return list of valid measures
+    if (remainingTokens.isEmpty() || Strings.nullToEmpty(remainingTokens.get(0)).trim().isEmpty()) {
+      List<String> measureNames = ResultsRow.measureNames(resultsRow.getTrade());
+      return EvaluationResult.failure("No measure specified. Use one of: {}", measureNames);
```
Comment (jonathansenior) [inline modules/report/src/main/java/com/opengamma/strata/report/framework/expression/RootEvaluator.java]: Is this tested?
